services:
  app:
    build: .
    environment:
      - APP_PORT=${APP_PORT}
      - DB_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/
    image: app
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/src

  mongodb:
    image: mongo
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/
      ME_CONFIG_BASICAUTH: false
volumes:
  dbdata6: